#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy
# Configure HAProxy
server_config=\
"
frontend  joshua-frontend
        bind *:80
        mode http
        default_backend joshua-backend
backend joshua-backend
        balance roundrobin
        server 139835-web-01 34.229.69.144:80 check
        server 139835-web-02 3.84.168.74:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart

# Test HAProxy configuration
curl -s http://localhost:80/ | grep -q "Hello World!"
if [ $? -eq 0 ]; then
    echo "HAProxy installed and configured successfully!"
else
    echo "HAProxy configuration failed!"
fi
